/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/DarthVader.glb -o src/components/DarthVader.jsx -k -r public 
*/

import React, { useEffect, useRef, useState } from 'react'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'

export function DarthVader(props) {
  const { nodes, materials } = useGLTF('/models/DarthVader.glb')
  const {animations: idleAnimation} = useFBX("/animations/DarthVader_Idle.fbx")
  const {animations: walkingAnimation} = useFBX("/animations/DarthVader_Walking.fbx")

  const group = useRef();
  idleAnimation[0].name = "Idle";
  walkingAnimation[0].name = "Walking";

  const { actions } = useAnimations([idleAnimation[0], walkingAnimation[0]], group);
  const [animation, setAnimation] = useState("Idle");
  useEffect(() => {
    actions[animation].reset().fadeIn(0.5).play();
    return () => actions[animation].fadeOut(0.5);

  }, [animation])

  return (
    <group {...props} dispose={null} ref={group}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials['Material.006']} />
        <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials['Material.007']} />
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.008']} />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['Material.009']} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.010']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/DarthVader.glb');
useFBX.preload("/animations/DarthVader_Idle.fbx");
useFBX.preload("/animations/DarthVader_Walking.fbx");