/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/purpleplanet.glb -o src/components/PurplePlant.jsx -r public 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function PurplePlanet(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/purpleplanet.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Clouds_1" rotation={[0, 0, -0.011]} scale={1.019}>
              <mesh name="Clouds_1_0" geometry={nodes.Clouds_1_0.geometry} material={materials.Clouds_1} />
            </group>
            <group name="Planet" rotation={[0, 0, 1.565]}>
              <group name="Clouds_0" rotation={[0, 0, -Math.PI / 2]} scale={1.013}>
                <mesh name="Clouds_0_0" geometry={nodes.Clouds_0_0.geometry} material={materials.Clouds_0} />
              </group>
              <mesh name="Planet_0" geometry={nodes.Planet_0.geometry} material={materials.PurplePlanet} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/purpleplanet.glb')
