/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/TV.glb -o src/components/TV.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function TV(props) {
  const { nodes, materials } = useGLTF('/models/TV.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials.TexMap} />
    </group>
  )
}

useGLTF.preload('/models/TV.glb')
